language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda
  - panda --notests installdeps .
  - panda --notests install IO::Socket::SSL
script:
  - PERL6LIB=$PWD/blib/lib prove -e perl6 -r t/
sudo: false
